stages:
  - build
  - upload
  - release

variables:
  JAR_FILE: "cogent-assembly-${CI_COMMIT_SHORT_SHA}.jar"
  JAR_FILE_LATEST: "cogent-assembly-latest.jar"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/cogent-builds"

build:
  stage: build
  image: openjdk:8
  # rules:
  #   - if: $CI_COMMIT_TAG
  #     when: never                                             # Do not run this job when a tag is created manually
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH             # Run this job when commits are pushed or merged to the default branch
  before_script:
    # Enable the usage of sources over https
    - apt-get update -yqq
    - apt-get install apt-transport-https -yqq
    # Add keyserver for SBT
    - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
    - mkdir -p /root/.gnupg
    - gpg --recv-keys --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --keyserver hkp://keyserver.ubuntu.com:80 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    - chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
    # Install SBT
    - apt-get update -yqq
    - apt-get install sbt -yqq
    # Log the sbt version
    - sbt sbtVersion
  script:
    - mkdir bin
    - sbt assembly
    - mv target/scala-3.2.0/cogent-assembly-1.0.jar bin/${JAR_FILE}
    - cp bin/${JAR_FILE} bin/${JAR_FILE_LATEST}
  artifacts:
    paths:
      - bin/

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                             # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH             # Run this job when commits are pushed or merged to the default branch
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${JAR_FILE} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_SHORT_SHA}/${JAR_FILE}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${JAR_FILE_LATEST} "${PACKAGE_REGISTRY_URL}/latest/${JAR_FILE_LATEST}"
