@startuml
    state A {
        note "B" as B
        [*] -> C
        state C
        state D
        C -> D: a \n [g and {status==12} and not in F] \n / w
        C -> D: a [h] / x
        D -> C : a [g] / w
        D -> C : a [h] / x
        D -> C : a [else] / y
        --
        note "E" as E
        [*] -> F
        state F
        state G
        state H <<choice>>
        F -> H: a / y
        H -> F: [ok] 
        H -> G: [else]
        F --> E : XYZ
        --
        [*] -> W
        state W {
            [*] -> W1
            state W1
            state WC <<choice>>
            state W2 {
                [*] -> W21
                state W21
                state W22
                W22 -> WC : a / p
            }
            state W3 {
                [*] -> W31
                state W31
                state W32
            }
            WC -> W1 : [A || OK] / q
            WC -> W32 : [B] / r
        }
        --
        note "Z" as Z
        [*] -> X
        state X
        state Y
        X -> Y: after( 3s ) \n [g and {status==12} and not in F] \n / w
    }
    state A
@enduml
