@startuml
    state A {
        note "B" as B
        [*] -> C
        state C
        state D
        C -> D: a [g] / w
        C -> D: a [h] / x
        D -> C : a [g] / w
        D -> C : a [h] / x
        D -> C : a [else] / y
        --
        note "E" as E
        [*] -> F
        state F
        state G
        state H <<choice>>
        F -> H: a / y
        H -> F: [ok] 
        H -> G: [else]
        F --> E : XYZ
        --
        [*] -> W
        state W {
            state X
            X -> X
        }
    }
    state A
@enduml
