@startuml
state A 
state B
state Little <<submachine>> {
  state entry1 <<entryPoint>>
  state entry2 <<entryPoint>>
  state exit3 <<exitPoint>>
}

[*] -> A
A -> B : P
B --> entry1 : Q
A --> entry2 : R
exit3 --> A
@enduml

@startuml LittleSubmachine
state Little <<submachine>> {
  state entry1 <<entryPoint>>
  state entry2 <<entryPoint>>
  state sin1
  state sin2
  entry1 -> sin1 
  entry2 --> sin1 
  sin1 -> sin2 : V
  sin2 --> exitA <<exitPoint>>
}
@enduml
