@startuml
    state A {
        note "B" as B
        [*] -> C
        state C
        state D
        C -> D: a [g] / w
        C -> D: a [h] / x
        D -> C : a [g] / w
        D -> C : a [h] / x
        D -> C : a [else] / y
        --
        note "E" as E
        [*] -> F
        state F
        state G
        state H <<choice>>
        F -> H: a / y
        H -> F: [ok] 
        H -> G: [else]
        F --> E : XYZ
        --
        [*] -> W
        state W {
            [*] -> W1
            state W1
            state WC <<choice>>
            state W2 {
                [*] -> W21
                state W21
                state W22
                W22 -> WC : a / p
            }
            state W3 {
                [*] -> W31
                state W31
                state W32
            }
            WC -> W1 : [A] / q
            WC -> W32 : [B] / r
        }
    }
    state A
@enduml