@startuml

state A {
    state B
    state F
    state C
    state D
    state diamond_0 <<choice>>
    [*] -> B
    B -> diamond_0 : a [R]
    F --> diamond_0 : b 
    diamond_0 -> C : [P] / x
    diamond_0 --> D : [Q] / y
}
state E
A -> E : a / z
@enduml
