@startuml tautology_examples
state Tautologies {
    ' Should result in 5 warnings.

    state A0
    state B0
    state M0 <<choice>>
    state N0 <<choice>>
    state A1
    state B1
    state M1 <<choice>>
    state N1 <<choice>>
    [*] --> A0

    'Propositional ambiguity from a state CHECK
    A0 --> B0 : z [p and q]
    A0 --> B0 : z [p and r]
    A0 --> B0 : z [not p]

    'No propositional ambiguity from a state
    A1 --> B1 : z [p and q]
    A1 --> B1 : z [p and not q]
    A1 --> B1 : z [not p]

    'Propositional ambiguity from a choice CHECK
    'This example also has the possibility that all guards are false. CHECK
    A0 --> M0 : x
    M0 --> B0 : [p and q]
    M0 --> B0 : [p and r]
    M0 --> B0 : [not p]

    'No ambiguity from a choice
    A1 --> M1 : x
    M1 --> B1 : [p and q]
    M1 --> B1 : [p and not q]
    M1 --> B1 : [not p]

    'Propositional impossibility CHECK
    A0 --> N0 : y
    N0 --> B0 : [p]

    'Propositional impossibility
    A1 --> N1 : y
    N1 --> B1 : [p]
    N1 --> B1 : [not p]

    'This impossibility should be fine because it is from a state
    A1 --> B1 : v [p]

    'Else not needed CHECK
    A0 --> B0 : w [p]
    A0 --> B0 : w [not p]
    A0 --> B0 : w [else]

    'Else not unnecessary
    A1 --> B1 : w [p]
    A1 --> B1 : w [not p and q]
    A1 --> B1 : w [else]
}
@enduml