@startuml
    state IDLE 
    state RUNNING
    state C <<choice>>
    [*] -> IDLE
    IDLE -> C : GO
    C -> RUNNING : [ready?] / start
    C -> IDLE : [else]
    RUNNING -> IDLE : KILL / stop
    RUNNING --> IDLE : after(60s) / stop
@enduml
